task: 
  name: formation
  drone_model: Crazyflie
  formation: tetragon
algo:
  name: mappo
  train_every: 500
  num_minibatches: 32
  ppo_epochs: 4
  clip_param: 0.2
  entropy_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.995
  max_grad_norm: 10.0
  normalize_advantages: true
  reward_weights: null
  share_actor: true
  critic_input: state
  value_learning: combined
  actor:
    lr: 0.0005
    lr_scheduler: null
    lr_scheduler_kwargs: null
    hidden_units:
    - 128
    - 128
    weight_decay: 0.0
    gain: 0.01
    use_attn: false
    attn_encoder: PartialAttentionEncoder
    use_orthogonal: true
  critic:
    num_critics: 1
    value_norm:
      class: ValueNorm1
      kwargs:
        beta: 0.995
    lr: 0.0005
    lr_scheduler: null
    lr_scheduler_kwargs: null
    hidden_units:
    - 128
    - 128
    weight_decay: 0.0
    gain: 0.01
    use_huber_loss: true
    huber_delta: 10
    use_attn: false
    attn_encoder: PartialAttentionEncoder
    use_feature_normalization: true
    use_orthogonal: true
headless: true
env:
  num_envs: 1024
  env_spacing: 2.5
  max_episode_length: 500
sim:
  dt: 0.016
  substeps: 1
  gravity:
  - 0
  - 0
  - -9.81
  replicate_physics: false
  use_flatcache: true
  use_gpu_pipeline: true
  device: cuda:0
  gpu_max_rigid_contact_count: 524288
  gpu_max_rigid_patch_count: 81920
  gpu_found_lost_pairs_capacity: 4194304
  gpu_found_lost_aggregate_pairs_capacity: 33554432
  gpu_total_aggregate_pairs_capacity: 4194304
  gpu_max_soft_body_contacts: 1048576
  gpu_max_particle_contacts: 1048576
  gpu_heap_capacity: 67108864
  gpu_temp_buffer_capacity: 16777216
  gpu_max_num_partitions: 8
viewer:
  eye:
  - 7.5
  - 7.5
  - 7.5
  lookat:
  - 0.0
  - 0.0
  - 0.0
wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}
  job_type: train
  entity: marl-drones
  project: gpu-onpolicy
  mode: online
  run_id: null
  run_path: null
  monitor_gym: true
  log_code: true
  tags: null
